<?php

/**
 * BasesfDoctrineSimpleForumCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $stripped_name
 * @property string $description
 * @property integer $rank
 * @property Doctrine_Collection $Forums
 * 
 * @method integer                       getId()            Returns the current record's "id" value
 * @method string                        getName()          Returns the current record's "name" value
 * @method string                        getStrippedName()  Returns the current record's "stripped_name" value
 * @method string                        getDescription()   Returns the current record's "description" value
 * @method integer                       getRank()          Returns the current record's "rank" value
 * @method Doctrine_Collection           getForums()        Returns the current record's "Forums" collection
 * @method sfDoctrineSimpleForumCategory setId()            Sets the current record's "id" value
 * @method sfDoctrineSimpleForumCategory setName()          Sets the current record's "name" value
 * @method sfDoctrineSimpleForumCategory setStrippedName()  Sets the current record's "stripped_name" value
 * @method sfDoctrineSimpleForumCategory setDescription()   Sets the current record's "description" value
 * @method sfDoctrineSimpleForumCategory setRank()          Sets the current record's "rank" value
 * @method sfDoctrineSimpleForumCategory setForums()        Sets the current record's "Forums" collection
 * 
 * @package    leerling
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasesfDoctrineSimpleForumCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_doctrine_simple_forum_category');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('stripped_name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('rank', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfDoctrineSimpleForumForum as Forums', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $sluggable0 = new Doctrine_Template_Sluggable();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
        $this->actAs($sluggable0);
    }
}