<?php

/**
 * BasesfDoctrineSimpleForumTopicView
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $topic_id
 * @property sfGuardUser $sfGuardUser
 * @property sfDoctrineSimpleForumTopic $sfDoctrineSimpleForumTopic
 * 
 * @method integer                        getId()                         Returns the current record's "id" value
 * @method integer                        getUserId()                     Returns the current record's "user_id" value
 * @method integer                        getTopicId()                    Returns the current record's "topic_id" value
 * @method sfGuardUser                    getSfGuardUser()                Returns the current record's "sfGuardUser" value
 * @method sfDoctrineSimpleForumTopic     getSfDoctrineSimpleForumTopic() Returns the current record's "sfDoctrineSimpleForumTopic" value
 * @method sfDoctrineSimpleForumTopicView setId()                         Sets the current record's "id" value
 * @method sfDoctrineSimpleForumTopicView setUserId()                     Sets the current record's "user_id" value
 * @method sfDoctrineSimpleForumTopicView setTopicId()                    Sets the current record's "topic_id" value
 * @method sfDoctrineSimpleForumTopicView setSfGuardUser()                Sets the current record's "sfGuardUser" value
 * @method sfDoctrineSimpleForumTopicView setSfDoctrineSimpleForumTopic() Sets the current record's "sfDoctrineSimpleForumTopic" value
 * 
 * @package    leerling
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasesfDoctrineSimpleForumTopicView extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_doctrine_simple_forum_topic_view');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('topic_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('sfDoctrineSimpleForumTopic', array(
             'local' => 'topic_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}