<?php

/**
 * BasesfDoctrineSimpleForumTopic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property boolean $is_sticked
 * @property boolean $is_locked
 * @property integer $forum_id
 * @property integer $latest_post_id
 * @property integer $user_id
 * @property string $stripped_title
 * @property integer $nb_posts
 * @property integer $nb_views
 * @property sfDoctrineSimpleForumForum $Forum
 * @property sfGuardUser $User
 * @property sfDoctrineSimpleForumPost $LastPost
 * @property Doctrine_Collection $Posts
 * @property Doctrine_Collection $sfDoctrineSimpleForumTopicView
 * 
 * @method integer                    getId()                             Returns the current record's "id" value
 * @method string                     getTitle()                          Returns the current record's "title" value
 * @method boolean                    getIsSticked()                      Returns the current record's "is_sticked" value
 * @method boolean                    getIsLocked()                       Returns the current record's "is_locked" value
 * @method integer                    getForumId()                        Returns the current record's "forum_id" value
 * @method integer                    getLatestPostId()                   Returns the current record's "latest_post_id" value
 * @method integer                    getUserId()                         Returns the current record's "user_id" value
 * @method string                     getStrippedTitle()                  Returns the current record's "stripped_title" value
 * @method integer                    getNbPosts()                        Returns the current record's "nb_posts" value
 * @method integer                    getNbViews()                        Returns the current record's "nb_views" value
 * @method sfDoctrineSimpleForumForum getForum()                          Returns the current record's "Forum" value
 * @method sfGuardUser                getUser()                           Returns the current record's "User" value
 * @method sfDoctrineSimpleForumPost  getLastPost()                       Returns the current record's "LastPost" value
 * @method Doctrine_Collection        getPosts()                          Returns the current record's "Posts" collection
 * @method Doctrine_Collection        getSfDoctrineSimpleForumTopicView() Returns the current record's "sfDoctrineSimpleForumTopicView" collection
 * @method sfDoctrineSimpleForumTopic setId()                             Sets the current record's "id" value
 * @method sfDoctrineSimpleForumTopic setTitle()                          Sets the current record's "title" value
 * @method sfDoctrineSimpleForumTopic setIsSticked()                      Sets the current record's "is_sticked" value
 * @method sfDoctrineSimpleForumTopic setIsLocked()                       Sets the current record's "is_locked" value
 * @method sfDoctrineSimpleForumTopic setForumId()                        Sets the current record's "forum_id" value
 * @method sfDoctrineSimpleForumTopic setLatestPostId()                   Sets the current record's "latest_post_id" value
 * @method sfDoctrineSimpleForumTopic setUserId()                         Sets the current record's "user_id" value
 * @method sfDoctrineSimpleForumTopic setStrippedTitle()                  Sets the current record's "stripped_title" value
 * @method sfDoctrineSimpleForumTopic setNbPosts()                        Sets the current record's "nb_posts" value
 * @method sfDoctrineSimpleForumTopic setNbViews()                        Sets the current record's "nb_views" value
 * @method sfDoctrineSimpleForumTopic setForum()                          Sets the current record's "Forum" value
 * @method sfDoctrineSimpleForumTopic setUser()                           Sets the current record's "User" value
 * @method sfDoctrineSimpleForumTopic setLastPost()                       Sets the current record's "LastPost" value
 * @method sfDoctrineSimpleForumTopic setPosts()                          Sets the current record's "Posts" collection
 * @method sfDoctrineSimpleForumTopic setSfDoctrineSimpleForumTopicView() Sets the current record's "sfDoctrineSimpleForumTopicView" collection
 * 
 * @package    leerling
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasesfDoctrineSimpleForumTopic extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_doctrine_simple_forum_topic');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('is_sticked', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('is_locked', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('forum_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('latest_post_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('stripped_title', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('nb_posts', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '4',
             ));
        $this->hasColumn('nb_views', 'integer', 10, array(
             'type' => 'integer',
             'default' => 0,
             'length' => '10',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfDoctrineSimpleForumForum as Forum', array(
             'local' => 'forum_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('sfDoctrineSimpleForumPost as LastPost', array(
             'local' => 'latest_post_id',
             'foreign' => 'id'));

        $this->hasMany('sfDoctrineSimpleForumPost as Posts', array(
             'local' => 'id',
             'foreign' => 'topic_id'));

        $this->hasMany('sfDoctrineSimpleForumTopicView', array(
             'local' => 'id',
             'foreign' => 'topic_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $sluggable0 = new Doctrine_Template_Sluggable();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
        $this->actAs($sluggable0);
    }
}