<?php

/**
 * BasesfDoctrineSimpleForumForum
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property integer $rank
 * @property integer $category_id
 * @property string $stripped_name
 * @property integer $latest_post_id
 * @property integer $nb_posts
 * @property integer $nb_topics
 * @property sfDoctrineSimpleForumCategory $Category
 * @property sfDoctrineSimpleForumPost $LastPost
 * @property Doctrine_Collection $sfDoctrineSimpleForumTopic
 * 
 * @method integer                       getId()                         Returns the current record's "id" value
 * @method string                        getName()                       Returns the current record's "name" value
 * @method string                        getDescription()                Returns the current record's "description" value
 * @method integer                       getRank()                       Returns the current record's "rank" value
 * @method integer                       getCategoryId()                 Returns the current record's "category_id" value
 * @method string                        getStrippedName()               Returns the current record's "stripped_name" value
 * @method integer                       getLatestPostId()               Returns the current record's "latest_post_id" value
 * @method integer                       getNbPosts()                    Returns the current record's "nb_posts" value
 * @method integer                       getNbTopics()                   Returns the current record's "nb_topics" value
 * @method sfDoctrineSimpleForumCategory getCategory()                   Returns the current record's "Category" value
 * @method sfDoctrineSimpleForumPost     getLastPost()                   Returns the current record's "LastPost" value
 * @method Doctrine_Collection           getSfDoctrineSimpleForumTopic() Returns the current record's "sfDoctrineSimpleForumTopic" collection
 * @method sfDoctrineSimpleForumForum    setId()                         Sets the current record's "id" value
 * @method sfDoctrineSimpleForumForum    setName()                       Sets the current record's "name" value
 * @method sfDoctrineSimpleForumForum    setDescription()                Sets the current record's "description" value
 * @method sfDoctrineSimpleForumForum    setRank()                       Sets the current record's "rank" value
 * @method sfDoctrineSimpleForumForum    setCategoryId()                 Sets the current record's "category_id" value
 * @method sfDoctrineSimpleForumForum    setStrippedName()               Sets the current record's "stripped_name" value
 * @method sfDoctrineSimpleForumForum    setLatestPostId()               Sets the current record's "latest_post_id" value
 * @method sfDoctrineSimpleForumForum    setNbPosts()                    Sets the current record's "nb_posts" value
 * @method sfDoctrineSimpleForumForum    setNbTopics()                   Sets the current record's "nb_topics" value
 * @method sfDoctrineSimpleForumForum    setCategory()                   Sets the current record's "Category" value
 * @method sfDoctrineSimpleForumForum    setLastPost()                   Sets the current record's "LastPost" value
 * @method sfDoctrineSimpleForumForum    setSfDoctrineSimpleForumTopic() Sets the current record's "sfDoctrineSimpleForumTopic" collection
 * 
 * @package    leerling
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasesfDoctrineSimpleForumForum extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_doctrine_simple_forum_forum');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('rank', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('stripped_name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('latest_post_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('nb_posts', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('nb_topics', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfDoctrineSimpleForumCategory as Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('sfDoctrineSimpleForumPost as LastPost', array(
             'local' => 'latest_post_id',
             'foreign' => 'id'));

        $this->hasMany('sfDoctrineSimpleForumTopic', array(
             'local' => 'id',
             'foreign' => 'forum_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $sluggable0 = new Doctrine_Template_Sluggable();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
        $this->actAs($sluggable0);
    }
}