<?php

/**
 * BaseLinks
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $image
 * @property string $url
 * @property boolean $is_active
 * 
 * @method string  getTitle()     Returns the current record's "title" value
 * @method string  getImage()     Returns the current record's "image" value
 * @method string  getUrl()       Returns the current record's "url" value
 * @method boolean getIsActive()  Returns the current record's "is_active" value
 * @method Links   setTitle()     Sets the current record's "title" value
 * @method Links   setImage()     Sets the current record's "image" value
 * @method Links   setUrl()       Sets the current record's "url" value
 * @method Links   setIsActive()  Sets the current record's "is_active" value
 * 
 * @package    leerling
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseLinks extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('links');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('url', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '1000',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}