<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseleerlijnKernbegripVak extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('leerlijn_kernbegrip_vak');
        $this->hasColumn('kernbegrip_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('vak_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('leerlijnKernbegrip', array(
             'local' => 'kernbegrip_id',
             'foreign' => 'id'));

        $this->hasOne('leerlijnVak', array(
             'local' => 'vak_id',
             'foreign' => 'id'));
    }
}