<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseleerlijnNiveau extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('leerlijn_niveau');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('leerjaar_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('leerlijnLeerjaar as Leerjaar', array(
             'local' => 'leerjaar_id',
             'foreign' => 'id'));

        $this->hasMany('leerlijnSleutelinzicht as Sleutelinzicht', array(
             'local' => 'id',
             'foreign' => 'niveau_id'));

        $sortable0 = new Doctrine_Template_Sortable();
        $this->actAs($sortable0);
    }
}