<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseleerlijnLeerjaar extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('leerlijn_leerjaar');
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('leerlijnNiveau as Niveau', array(
             'local' => 'id',
             'foreign' => 'leerjaar_id'));

        $this->hasMany('leerlijnThema as Thema', array(
             'refClass' => 'leerlijnLeerjaarThema',
             'local' => 'leerjaar_id',
             'foreign' => 'thema_id'));

        $this->hasMany('leerlijnLeerjaarThema', array(
             'local' => 'id',
             'foreign' => 'leerjaar_id'));

        $this->hasMany('leerlijnSleutelinzichtLeerjaar', array(
             'local' => 'id',
             'foreign' => 'leerjaar_id'));
    }
}