<?php

/**
 * BaseleerlijnLeerjaar
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $image
 * @property string $name
 * @property Doctrine_Collection $Niveau
 * @property Doctrine_Collection $Thema
 * @property Doctrine_Collection $leerlijnLeerjaarThema
 * @property Doctrine_Collection $leerlijnSleutelinzichtLeerjaar
 * 
 * @method string              getImage()                          Returns the current record's "image" value
 * @method string              getName()                           Returns the current record's "name" value
 * @method Doctrine_Collection getNiveau()                         Returns the current record's "Niveau" collection
 * @method Doctrine_Collection getThema()                          Returns the current record's "Thema" collection
 * @method Doctrine_Collection getLeerlijnLeerjaarThema()          Returns the current record's "leerlijnLeerjaarThema" collection
 * @method Doctrine_Collection getLeerlijnSleutelinzichtLeerjaar() Returns the current record's "leerlijnSleutelinzichtLeerjaar" collection
 * @method leerlijnLeerjaar    setImage()                          Sets the current record's "image" value
 * @method leerlijnLeerjaar    setName()                           Sets the current record's "name" value
 * @method leerlijnLeerjaar    setNiveau()                         Sets the current record's "Niveau" collection
 * @method leerlijnLeerjaar    setThema()                          Sets the current record's "Thema" collection
 * @method leerlijnLeerjaar    setLeerlijnLeerjaarThema()          Sets the current record's "leerlijnLeerjaarThema" collection
 * @method leerlijnLeerjaar    setLeerlijnSleutelinzichtLeerjaar() Sets the current record's "leerlijnSleutelinzichtLeerjaar" collection
 * 
 * @package    leerling
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseleerlijnLeerjaar extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('leerlijn_leerjaar');
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('leerlijnNiveau as Niveau', array(
             'local' => 'id',
             'foreign' => 'leerjaar_id'));

        $this->hasMany('leerlijnThema as Thema', array(
             'refClass' => 'leerlijnLeerjaarThema',
             'local' => 'leerjaar_id',
             'foreign' => 'thema_id'));

        $this->hasMany('leerlijnLeerjaarThema', array(
             'local' => 'id',
             'foreign' => 'leerjaar_id'));

        $this->hasMany('leerlijnSleutelinzichtLeerjaar', array(
             'local' => 'id',
             'foreign' => 'leerjaar_id'));
    }
}