<?php

/**
 * BaseleerlijnLeerjaarThema
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $leerjaar_id
 * @property integer $thema_id
 * @property leerlijnThema $leerlijnThema
 * @property leerlijnLeerjaar $leerlijnLeerjaar
 * 
 * @method integer               getLeerjaarId()       Returns the current record's "leerjaar_id" value
 * @method integer               getThemaId()          Returns the current record's "thema_id" value
 * @method leerlijnThema         getLeerlijnThema()    Returns the current record's "leerlijnThema" value
 * @method leerlijnLeerjaar      getLeerlijnLeerjaar() Returns the current record's "leerlijnLeerjaar" value
 * @method leerlijnLeerjaarThema setLeerjaarId()       Sets the current record's "leerjaar_id" value
 * @method leerlijnLeerjaarThema setThemaId()          Sets the current record's "thema_id" value
 * @method leerlijnLeerjaarThema setLeerlijnThema()    Sets the current record's "leerlijnThema" value
 * @method leerlijnLeerjaarThema setLeerlijnLeerjaar() Sets the current record's "leerlijnLeerjaar" value
 * 
 * @package    leerling
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseleerlijnLeerjaarThema extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('leerlijn_leerjaar_thema');
        $this->hasColumn('leerjaar_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('thema_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('leerlijnThema', array(
             'local' => 'thema_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('leerlijnLeerjaar', array(
             'local' => 'leerjaar_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}