<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasehelpArticle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('help_article');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

}