<?php

/**
 * BaseleerlijnKernbegripThema
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $kernbegrip_id
 * @property integer $thema_id
 * @property leerlijnThema $leerlijnThema
 * @property leerlijnKernbegrip $leerlijnKernbegrip
 * 
 * @method integer                 getKernbegripId()       Returns the current record's "kernbegrip_id" value
 * @method integer                 getThemaId()            Returns the current record's "thema_id" value
 * @method leerlijnThema           getLeerlijnThema()      Returns the current record's "leerlijnThema" value
 * @method leerlijnKernbegrip      getLeerlijnKernbegrip() Returns the current record's "leerlijnKernbegrip" value
 * @method leerlijnKernbegripThema setKernbegripId()       Sets the current record's "kernbegrip_id" value
 * @method leerlijnKernbegripThema setThemaId()            Sets the current record's "thema_id" value
 * @method leerlijnKernbegripThema setLeerlijnThema()      Sets the current record's "leerlijnThema" value
 * @method leerlijnKernbegripThema setLeerlijnKernbegrip() Sets the current record's "leerlijnKernbegrip" value
 * 
 * @package    leerling
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseleerlijnKernbegripThema extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('leerlijn_kernbegrip_thema');
        $this->hasColumn('kernbegrip_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('thema_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('leerlijnThema', array(
             'local' => 'thema_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('leerlijnKernbegrip', array(
             'local' => 'kernbegrip_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}