<?php

/**
 * BaseleerlijnThema
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description_humanics
 * @property string $description_arts
 * @property string $description_science
 * @property string $description_linguistics
 * @property string $image
 * @property Doctrine_Collection $Leerjaar
 * @property Doctrine_Collection $Kernbegrip
 * @property Doctrine_Collection $leerlijnLeerjaarThema
 * @property Doctrine_Collection $leerlijnKernbegripThema
 * 
 * @method string              getName()                    Returns the current record's "name" value
 * @method string              getDescriptionHumanics()     Returns the current record's "description_humanics" value
 * @method string              getDescriptionArts()         Returns the current record's "description_arts" value
 * @method string              getDescriptionScience()      Returns the current record's "description_science" value
 * @method string              getDescriptionLinguistics()  Returns the current record's "description_linguistics" value
 * @method string              getImage()                   Returns the current record's "image" value
 * @method Doctrine_Collection getLeerjaar()                Returns the current record's "Leerjaar" collection
 * @method Doctrine_Collection getKernbegrip()              Returns the current record's "Kernbegrip" collection
 * @method Doctrine_Collection getLeerlijnLeerjaarThema()   Returns the current record's "leerlijnLeerjaarThema" collection
 * @method Doctrine_Collection getLeerlijnKernbegripThema() Returns the current record's "leerlijnKernbegripThema" collection
 * @method leerlijnThema       setName()                    Sets the current record's "name" value
 * @method leerlijnThema       setDescriptionHumanics()     Sets the current record's "description_humanics" value
 * @method leerlijnThema       setDescriptionArts()         Sets the current record's "description_arts" value
 * @method leerlijnThema       setDescriptionScience()      Sets the current record's "description_science" value
 * @method leerlijnThema       setDescriptionLinguistics()  Sets the current record's "description_linguistics" value
 * @method leerlijnThema       setImage()                   Sets the current record's "image" value
 * @method leerlijnThema       setLeerjaar()                Sets the current record's "Leerjaar" collection
 * @method leerlijnThema       setKernbegrip()              Sets the current record's "Kernbegrip" collection
 * @method leerlijnThema       setLeerlijnLeerjaarThema()   Sets the current record's "leerlijnLeerjaarThema" collection
 * @method leerlijnThema       setLeerlijnKernbegripThema() Sets the current record's "leerlijnKernbegripThema" collection
 * 
 * @package    leerling
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseleerlijnThema extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('leerlijn_thema');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('description_humanics', 'string', 4000, array(
             'type' => 'string',
             'length' => '4000',
             ));
        $this->hasColumn('description_arts', 'string', 4000, array(
             'type' => 'string',
             'length' => '4000',
             ));
        $this->hasColumn('description_science', 'string', 4000, array(
             'type' => 'string',
             'length' => '4000',
             ));
        $this->hasColumn('description_linguistics', 'string', 4000, array(
             'type' => 'string',
             'length' => '4000',
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('leerlijnLeerjaar as Leerjaar', array(
             'refClass' => 'leerlijnLeerjaarThema',
             'local' => 'thema_id',
             'foreign' => 'leerjaar_id'));

        $this->hasMany('leerlijnKernbegrip as Kernbegrip', array(
             'refClass' => 'leerlijnKernbegripThema',
             'local' => 'thema_id',
             'foreign' => 'kernbegrip_id'));

        $this->hasMany('leerlijnLeerjaarThema', array(
             'local' => 'id',
             'foreign' => 'thema_id'));

        $this->hasMany('leerlijnKernbegripThema', array(
             'local' => 'id',
             'foreign' => 'thema_id'));
    }
}