<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseleerlijnSleutelinzicht extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('leerlijn_sleutelinzicht');
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '4000',
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('niveau_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('kernbegrip_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('leerlijnKernbegrip as Kernbegrip', array(
             'local' => 'kernbegrip_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('leerlijnNiveau as Niveau', array(
             'local' => 'niveau_id',
             'foreign' => 'id'));

        $this->hasOne('leerlijnStatus as Status', array(
             'local' => 'id',
             'foreign' => 'sleutelinzicht_id'));

        $this->hasMany('leerlijnSleutelinzichtLeerjaar', array(
             'local' => 'id',
             'foreign' => 'sleutelinzicht_id'));
    }
}