<?php

/**
 * BaseleerlijnKern
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $summary
 * @property string $description
 * @property string $image
 * @property integer $leergebied_id
 * @property leerlijnLeergebied $Leergebied
 * @property Doctrine_Collection $Kernbegrip
 * @property Doctrine_Collection $leerlijnKernbegripKern
 * 
 * @method string              getName()                   Returns the current record's "name" value
 * @method string              getSummary()                Returns the current record's "summary" value
 * @method string              getDescription()            Returns the current record's "description" value
 * @method string              getImage()                  Returns the current record's "image" value
 * @method integer             getLeergebiedId()           Returns the current record's "leergebied_id" value
 * @method leerlijnLeergebied  getLeergebied()             Returns the current record's "Leergebied" value
 * @method Doctrine_Collection getKernbegrip()             Returns the current record's "Kernbegrip" collection
 * @method Doctrine_Collection getLeerlijnKernbegripKern() Returns the current record's "leerlijnKernbegripKern" collection
 * @method leerlijnKern        setName()                   Sets the current record's "name" value
 * @method leerlijnKern        setSummary()                Sets the current record's "summary" value
 * @method leerlijnKern        setDescription()            Sets the current record's "description" value
 * @method leerlijnKern        setImage()                  Sets the current record's "image" value
 * @method leerlijnKern        setLeergebiedId()           Sets the current record's "leergebied_id" value
 * @method leerlijnKern        setLeergebied()             Sets the current record's "Leergebied" value
 * @method leerlijnKern        setKernbegrip()             Sets the current record's "Kernbegrip" collection
 * @method leerlijnKern        setLeerlijnKernbegripKern() Sets the current record's "leerlijnKernbegripKern" collection
 * 
 * @package    leerling
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseleerlijnKern extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('leerlijn_kern');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('summary', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'length' => '4000',
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('leergebied_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('leerlijnLeergebied as Leergebied', array(
             'local' => 'leergebied_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('leerlijnKernbegrip as Kernbegrip', array(
             'refClass' => 'leerlijnKernbegripKern',
             'local' => 'kern_id',
             'foreign' => 'kernbegrip_id'));

        $this->hasMany('leerlijnKernbegripKern', array(
             'local' => 'id',
             'foreign' => 'kern_id'));
    }
}