<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseideaItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('idea_item');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('body', 'string', 5000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '5000',
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Vraag',
              1 => 'Probleem',
              2 => 'Idee',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('parent_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('ideaItem as Followup', array(
             'local' => 'parent_id',
             'foreign' => 'id'));

        $this->hasMany('ideaItem as Parent', array(
             'local' => 'id',
             'foreign' => 'parent_id'));

        $this->hasMany('ideaResponse as Response', array(
             'local' => 'id',
             'foreign' => 'item_id'));
    }
}