<?php

/**
 * BaseleerlijnEindterm
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $summary
 * @property string $description
 * @property string $image
 * @property integer $domein_id
 * @property leerlijnDomein $Domein
 * @property Doctrine_Collection $Kernbegrip
 * @property Doctrine_Collection $leerlijnKernbegripEindterm
 * 
 * @method string              getName()                       Returns the current record's "name" value
 * @method string              getSummary()                    Returns the current record's "summary" value
 * @method string              getDescription()                Returns the current record's "description" value
 * @method string              getImage()                      Returns the current record's "image" value
 * @method integer             getDomeinId()                   Returns the current record's "domein_id" value
 * @method leerlijnDomein      getDomein()                     Returns the current record's "Domein" value
 * @method Doctrine_Collection getKernbegrip()                 Returns the current record's "Kernbegrip" collection
 * @method Doctrine_Collection getLeerlijnKernbegripEindterm() Returns the current record's "leerlijnKernbegripEindterm" collection
 * @method leerlijnEindterm    setName()                       Sets the current record's "name" value
 * @method leerlijnEindterm    setSummary()                    Sets the current record's "summary" value
 * @method leerlijnEindterm    setDescription()                Sets the current record's "description" value
 * @method leerlijnEindterm    setImage()                      Sets the current record's "image" value
 * @method leerlijnEindterm    setDomeinId()                   Sets the current record's "domein_id" value
 * @method leerlijnEindterm    setDomein()                     Sets the current record's "Domein" value
 * @method leerlijnEindterm    setKernbegrip()                 Sets the current record's "Kernbegrip" collection
 * @method leerlijnEindterm    setLeerlijnKernbegripEindterm() Sets the current record's "leerlijnKernbegripEindterm" collection
 * 
 * @package    leerling
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseleerlijnEindterm extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('leerlijn_eindterm');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('summary', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'length' => '4000',
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('domein_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('leerlijnDomein as Domein', array(
             'local' => 'domein_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('leerlijnKernbegrip as Kernbegrip', array(
             'refClass' => 'leerlijnKernbegripEindterm',
             'local' => 'eindterm_id',
             'foreign' => 'kernbegrip_id'));

        $this->hasMany('leerlijnKernbegripEindterm', array(
             'local' => 'id',
             'foreign' => 'eindterm_id'));
    }
}