<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseleerlijnStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('leerlijn_status');
        $this->hasColumn('sleutelinzicht_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('profile_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('state', 'integer', 2, array(
             'type' => 'integer',
             'length' => '2',
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('sfGuardUserProfile as User', array(
             'local' => 'profile_id',
             'foreign' => 'id'));

        $this->hasOne('leerlijnSleutelinzicht as Sleutelinzicht', array(
             'local' => 'sleutelinzicht_id',
             'foreign' => 'id'));
    }
}