<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseideaResponse extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('idea_response');
        $this->hasColumn('body', 'string', 5000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '5000',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('item_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('ideaItem as Item', array(
             'local' => 'item_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}