<?php

/**
 * BaseleerlijnKernbegrip
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $summary
 * @property string $description
 * @property string $image
 * @property integer $thema_id
 * @property Doctrine_Collection $Kern
 * @property Doctrine_Collection $Eindterm
 * @property Doctrine_Collection $Thema
 * @property Doctrine_Collection $Sleutelinzicht
 * @property Doctrine_Collection $leerlijnKernbegripEindterm
 * @property Doctrine_Collection $leerlijnKernbegripKern
 * @property Doctrine_Collection $leerlijnKernbegripThema
 * @property Doctrine_Collection $Expert
 * @property Doctrine_Collection $expertKernbegrip
 * 
 * @method string              getName()                       Returns the current record's "name" value
 * @method string              getSummary()                    Returns the current record's "summary" value
 * @method string              getDescription()                Returns the current record's "description" value
 * @method string              getImage()                      Returns the current record's "image" value
 * @method integer             getThemaId()                    Returns the current record's "thema_id" value
 * @method Doctrine_Collection getKern()                       Returns the current record's "Kern" collection
 * @method Doctrine_Collection getEindterm()                   Returns the current record's "Eindterm" collection
 * @method Doctrine_Collection getThema()                      Returns the current record's "Thema" collection
 * @method Doctrine_Collection getSleutelinzicht()             Returns the current record's "Sleutelinzicht" collection
 * @method Doctrine_Collection getLeerlijnKernbegripEindterm() Returns the current record's "leerlijnKernbegripEindterm" collection
 * @method Doctrine_Collection getLeerlijnKernbegripKern()     Returns the current record's "leerlijnKernbegripKern" collection
 * @method Doctrine_Collection getLeerlijnKernbegripThema()    Returns the current record's "leerlijnKernbegripThema" collection
 * @method Doctrine_Collection getExpert()                     Returns the current record's "Expert" collection
 * @method Doctrine_Collection getExpertKernbegrip()           Returns the current record's "expertKernbegrip" collection
 * @method leerlijnKernbegrip  setName()                       Sets the current record's "name" value
 * @method leerlijnKernbegrip  setSummary()                    Sets the current record's "summary" value
 * @method leerlijnKernbegrip  setDescription()                Sets the current record's "description" value
 * @method leerlijnKernbegrip  setImage()                      Sets the current record's "image" value
 * @method leerlijnKernbegrip  setThemaId()                    Sets the current record's "thema_id" value
 * @method leerlijnKernbegrip  setKern()                       Sets the current record's "Kern" collection
 * @method leerlijnKernbegrip  setEindterm()                   Sets the current record's "Eindterm" collection
 * @method leerlijnKernbegrip  setThema()                      Sets the current record's "Thema" collection
 * @method leerlijnKernbegrip  setSleutelinzicht()             Sets the current record's "Sleutelinzicht" collection
 * @method leerlijnKernbegrip  setLeerlijnKernbegripEindterm() Sets the current record's "leerlijnKernbegripEindterm" collection
 * @method leerlijnKernbegrip  setLeerlijnKernbegripKern()     Sets the current record's "leerlijnKernbegripKern" collection
 * @method leerlijnKernbegrip  setLeerlijnKernbegripThema()    Sets the current record's "leerlijnKernbegripThema" collection
 * @method leerlijnKernbegrip  setExpert()                     Sets the current record's "Expert" collection
 * @method leerlijnKernbegrip  setExpertKernbegrip()           Sets the current record's "expertKernbegrip" collection
 * 
 * @package    leerling
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseleerlijnKernbegrip extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('leerlijn_kernbegrip');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('summary', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'length' => '4000',
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('thema_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('leerlijnKern as Kern', array(
             'refClass' => 'leerlijnKernbegripKern',
             'local' => 'kernbegrip_id',
             'foreign' => 'kern_id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('leerlijnEindterm as Eindterm', array(
             'refClass' => 'leerlijnKernbegripEindterm',
             'local' => 'kernbegrip_id',
             'foreign' => 'eindterm_id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('leerlijnThema as Thema', array(
             'refClass' => 'leerlijnKernbegripThema',
             'local' => 'kernbegrip_id',
             'foreign' => 'thema_id'));

        $this->hasMany('leerlijnSleutelinzicht as Sleutelinzicht', array(
             'local' => 'id',
             'foreign' => 'kernbegrip_id'));

        $this->hasMany('leerlijnKernbegripEindterm', array(
             'local' => 'id',
             'foreign' => 'kernbegrip_id'));

        $this->hasMany('leerlijnKernbegripKern', array(
             'local' => 'id',
             'foreign' => 'kernbegrip_id'));

        $this->hasMany('leerlijnKernbegripThema', array(
             'local' => 'id',
             'foreign' => 'kernbegrip_id'));

        $this->hasMany('expert as Expert', array(
             'refClass' => 'expertKernbegrip',
             'local' => 'kernbegrip_id',
             'foreign' => 'expert_id'));

        $this->hasMany('expertKernbegrip', array(
             'local' => 'id',
             'foreign' => 'kernbegrip_id'));
    }
}