<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseBlogPosts extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('blog_posts');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}