<?php

/**
 * BaseleerlijnNiveau
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $image
 * @property integer $leerjaar_id
 * @property leerlijnLeerjaar $Leerjaar
 * @property Doctrine_Collection $Sleutelinzicht
 * 
 * @method string              getName()           Returns the current record's "name" value
 * @method string              getImage()          Returns the current record's "image" value
 * @method integer             getLeerjaarId()     Returns the current record's "leerjaar_id" value
 * @method leerlijnLeerjaar    getLeerjaar()       Returns the current record's "Leerjaar" value
 * @method Doctrine_Collection getSleutelinzicht() Returns the current record's "Sleutelinzicht" collection
 * @method leerlijnNiveau      setName()           Sets the current record's "name" value
 * @method leerlijnNiveau      setImage()          Sets the current record's "image" value
 * @method leerlijnNiveau      setLeerjaarId()     Sets the current record's "leerjaar_id" value
 * @method leerlijnNiveau      setLeerjaar()       Sets the current record's "Leerjaar" value
 * @method leerlijnNiveau      setSleutelinzicht() Sets the current record's "Sleutelinzicht" collection
 * 
 * @package    leerling
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseleerlijnNiveau extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('leerlijn_niveau');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('leerjaar_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('leerlijnLeerjaar as Leerjaar', array(
             'local' => 'leerjaar_id',
             'foreign' => 'id'));

        $this->hasMany('leerlijnSleutelinzicht as Sleutelinzicht', array(
             'local' => 'id',
             'foreign' => 'niveau_id'));

        $sortable0 = new Doctrine_Template_Sortable();
        $this->actAs($sortable0);
    }
}