<?php

/**
 * BaseleerlijnStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sleutelinzicht_id
 * @property integer $user_id
 * @property enum $state
 * @property sfGuardUser $User
 * @property leerlijnSleutelinzicht $Sleutelinzicht
 * 
 * @method integer                getSleutelinzichtId()  Returns the current record's "sleutelinzicht_id" value
 * @method integer                getUserId()            Returns the current record's "user_id" value
 * @method enum                   getState()             Returns the current record's "state" value
 * @method sfGuardUser            getUser()              Returns the current record's "User" value
 * @method leerlijnSleutelinzicht getSleutelinzicht()    Returns the current record's "Sleutelinzicht" value
 * @method leerlijnStatus         setSleutelinzichtId()  Sets the current record's "sleutelinzicht_id" value
 * @method leerlijnStatus         setUserId()            Sets the current record's "user_id" value
 * @method leerlijnStatus         setState()             Sets the current record's "state" value
 * @method leerlijnStatus         setUser()              Sets the current record's "User" value
 * @method leerlijnStatus         setSleutelinzicht()    Sets the current record's "Sleutelinzicht" value
 * 
 * @package    leerling
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseleerlijnStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('leerlijn_status');
        $this->hasColumn('sleutelinzicht_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('state', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'not_started',
              1 => 'in_progress',
              2 => 'completed',
             ),
             'default' => 'not_started',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('leerlijnSleutelinzicht as Sleutelinzicht', array(
             'local' => 'sleutelinzicht_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}