<?php

/**
 * BaseleerlijnLeergebied
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property string $image
 * @property string $image_desc
 * @property Doctrine_Collection $Kern
 * @property Doctrine_Collection $Vak
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method string              getImage()       Returns the current record's "image" value
 * @method string              getImageDesc()   Returns the current record's "image_desc" value
 * @method Doctrine_Collection getKern()        Returns the current record's "Kern" collection
 * @method Doctrine_Collection getVak()         Returns the current record's "Vak" collection
 * @method leerlijnLeergebied  setName()        Sets the current record's "name" value
 * @method leerlijnLeergebied  setDescription() Sets the current record's "description" value
 * @method leerlijnLeergebied  setImage()       Sets the current record's "image" value
 * @method leerlijnLeergebied  setImageDesc()   Sets the current record's "image_desc" value
 * @method leerlijnLeergebied  setKern()        Sets the current record's "Kern" collection
 * @method leerlijnLeergebied  setVak()         Sets the current record's "Vak" collection
 * 
 * @package    leerling
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseleerlijnLeergebied extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('leerlijn_leergebied');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'length' => '4000',
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('image_desc', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('leerlijnKern as Kern', array(
             'local' => 'id',
             'foreign' => 'leergebied_id'));

        $this->hasMany('leerlijnVak as Vak', array(
             'local' => 'id',
             'foreign' => 'leergebied_id'));
    }
}