<?php

/**
 * Basechicken
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * 
 * @method string  getName() Returns the current record's "name" value
 * @method chicken setName() Sets the current record's "name" value
 * 
 * @package    leerling
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Basechicken extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('chicken');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}