<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class Baseexpert extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('expert');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'leerling',
              1 => 'ouder',
              2 => 'leraar',
              3 => 'anders',
             ),
             'default' => 'ouder',
             ));
        $this->hasColumn('profession', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'length' => '4000',
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('leerlijnKernbegrip as Kernbegrip', array(
             'refClass' => 'expertKernbegrip',
             'local' => 'expert_id',
             'foreign' => 'kernbegrip_id'));

        $this->hasMany('expertKernbegrip', array(
             'local' => 'id',
             'foreign' => 'expert_id'));

        $taggable0 = new Taggable();
        $this->actAs($taggable0);
    }
}