<?php

/**
 * BasehelpArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $body
 * 
 * @method string      getTitle() Returns the current record's "title" value
 * @method string      getBody()  Returns the current record's "body" value
 * @method helpArticle setTitle() Sets the current record's "title" value
 * @method helpArticle setBody()  Sets the current record's "body" value
 * 
 * @package    leerling
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasehelpArticle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('help_article');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}