<?php

/**
 * BaseleerlijnKernbegripKern
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $kernbegrip_id
 * @property integer $kern_id
 * @property leerlijnKernbegrip $leerlijnKernbegrip
 * @property leerlijnKern $leerlijnKern
 * 
 * @method integer                getKernbegripId()       Returns the current record's "kernbegrip_id" value
 * @method integer                getKernId()             Returns the current record's "kern_id" value
 * @method leerlijnKernbegrip     getLeerlijnKernbegrip() Returns the current record's "leerlijnKernbegrip" value
 * @method leerlijnKern           getLeerlijnKern()       Returns the current record's "leerlijnKern" value
 * @method leerlijnKernbegripKern setKernbegripId()       Sets the current record's "kernbegrip_id" value
 * @method leerlijnKernbegripKern setKernId()             Sets the current record's "kern_id" value
 * @method leerlijnKernbegripKern setLeerlijnKernbegrip() Sets the current record's "leerlijnKernbegrip" value
 * @method leerlijnKernbegripKern setLeerlijnKern()       Sets the current record's "leerlijnKern" value
 * 
 * @package    leerling
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseleerlijnKernbegripKern extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('leerlijn_kernbegrip_kern');
        $this->hasColumn('kernbegrip_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('kern_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('leerlijnKernbegrip', array(
             'local' => 'kernbegrip_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('leerlijnKern', array(
             'local' => 'kern_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}