<?php

/**
 * BaseexpertKernbegrip
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $expert_id
 * @property integer $kernbegrip_id
 * @property expert $expert
 * @property leerlijnKernbegrip $leerlijnKernbegrip
 * 
 * @method integer            getExpertId()           Returns the current record's "expert_id" value
 * @method integer            getKernbegripId()       Returns the current record's "kernbegrip_id" value
 * @method expert             getExpert()             Returns the current record's "expert" value
 * @method leerlijnKernbegrip getLeerlijnKernbegrip() Returns the current record's "leerlijnKernbegrip" value
 * @method expertKernbegrip   setExpertId()           Sets the current record's "expert_id" value
 * @method expertKernbegrip   setKernbegripId()       Sets the current record's "kernbegrip_id" value
 * @method expertKernbegrip   setExpert()             Sets the current record's "expert" value
 * @method expertKernbegrip   setLeerlijnKernbegrip() Sets the current record's "leerlijnKernbegrip" value
 * 
 * @package    leerling
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseexpertKernbegrip extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('expert_kernbegrip');
        $this->hasColumn('expert_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('kernbegrip_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('expert', array(
             'local' => 'expert_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('leerlijnKernbegrip', array(
             'local' => 'kernbegrip_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}