<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseleerlijnSleutelinzichtStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('leerlijn_sleutelinzicht_status');
        $this->hasColumn('sleutelinzicht_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('profile_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('sfGuardUserProfile', array(
             'local' => 'profile_id',
             'foreign' => 'id'));

        $this->hasOne('leerlijnSleutelinzicht', array(
             'local' => 'sleutelinzicht_id',
             'foreign' => 'id'));
    }
}