<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseleerlijnThema extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('leerlijn_thema');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('description_humanics', 'string', 4000, array(
             'type' => 'string',
             'length' => '4000',
             ));
        $this->hasColumn('description_arts', 'string', 4000, array(
             'type' => 'string',
             'length' => '4000',
             ));
        $this->hasColumn('description_science', 'string', 4000, array(
             'type' => 'string',
             'length' => '4000',
             ));
        $this->hasColumn('description_linguistics', 'string', 4000, array(
             'type' => 'string',
             'length' => '4000',
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasMany('leerlijnLeerjaar as Leerjaar', array(
             'refClass' => 'leerlijnLeerjaarThema',
             'local' => 'thema_id',
             'foreign' => 'leerjaar_id'));

        $this->hasMany('leerlijnKernbegrip as Kernbegrip', array(
             'refClass' => 'leerlijnKernbegripThema',
             'local' => 'thema_id',
             'foreign' => 'kernbegrip_id'));

        $this->hasMany('leerlijnLeerjaarThema', array(
             'local' => 'id',
             'foreign' => 'thema_id'));

        $this->hasMany('leerlijnKernbegripThema', array(
             'local' => 'id',
             'foreign' => 'thema_id'));
    }
}