<?php

/**
 * BaseBlogPosts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property string $body
 * @property boolean $private
 * 
 * @method string    getTitle()   Returns the current record's "title" value
 * @method string    getBody()    Returns the current record's "body" value
 * @method boolean   getPrivate() Returns the current record's "private" value
 * @method BlogPosts setTitle()   Sets the current record's "title" value
 * @method BlogPosts setBody()    Sets the current record's "body" value
 * @method BlogPosts setPrivate() Sets the current record's "private" value
 * 
 * @package    leerling
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseBlogPosts extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('blog_posts');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('private', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}