default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [default.css, main.css, admin.css]

  javascripts:    [jquery, checkboxes, admin]

  has_layout:     on
  layout:         layout
