<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/03/21 15:08:01
sfConfig::add(array(
  'app_sfDoctrineSimpleForumPlugin_use_markdown' => true,
  'app_sfDoctrineSimpleForumPlugin_sort_order' => 'ASC',
  'app_sfDoctrineSimpleForumPlugin_include_jquery' => false,
  'app_sfDoctrineSimpleForumPlugin_use_hints' => true,
  'app_sf_less_php_plugin_use_compression' => true,
  'app_sf_less_php_plugin_compile' => false,
  'app_posts_op_nieuwspagina' => 5,
  'app_invite' => true,
  'app_feedback_active' => true,
  'app_feedback_feedback_email' => array (
  0 => 'mathijs.henquet@gmail.com',
),
  'app_feedback_sender' => array (
  'email' => 'dnsleergemeenschap@gmail.com',
  'password' => '',
),
  'app_deadpixel_active' => true,
  'app_gravity_active' => false,
  'app_cowboy_active' => true,
  'app_chicken_active' => true,
  'app_cufon_active' => true,
  'app_sf_guard_plugin_profile_class' => 'sfGuardUserProfile',
  'app_sf_guard_plugin_profile_field_name' => 'user_id',
  'app_sfCombinePlugin_enabled' => true,
  'app_sfCombinePlugin_asset_version' => 1,
  'app_sfCombinePlugin_client_cache_max_age' => 10,
  'app_sfCombinePlugin_gzip' => false,
  'app_sfCombinePlugin_js' => array (
  'combine_skip' => 
  array (
    0 => 'main.js',
  ),
  'minify' => false,
  'minify_skip' => 
  array (
    0 => 'jquery.js',
  ),
  'pack' => false,
  'pack_skip' => NULL,
),
  'app_sfCombinePlugin_css' => array (
  'minify' => false,
),
  'app_swToolbox_cross_link_application' => array (
  'frontend' => 
  array (
    'enabled' => true,
    'load' => 
    array (
      'backend' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'dns.loc/backend_dev.php',
          'cache' => 'dns.loc/backend_dev.php',
          'prod' => 'beheer.dnsleerroutes.net',
        ),
      ),
    ),
  ),
  'backend' => 
  array (
    'enabled' => true,
    'load' => 
    array (
      'frontend' => 
      array (
        'routes' => NULL,
        'env' => 
        array (
          'dev' => 'dns.loc/frontend_dev.php',
          'cache' => 'dns.loc/frontend_cache.php',
          'prod' => 'dnsleerroutes.net',
        ),
      ),
    ),
  ),
),
  'app_sf_google_analytics_plugin_enabled' => true,
  'app_sf_google_analytics_plugin_profile_id' => 'UA-11396238-1',
  'app_sf_google_analytics_plugin_tracker' => 'google',
  'app_nahoWikiPlugin_start_page' => 'index',
  'app_nahoWikiPlugin_pagename_format' => 'a-z0-9\\-_',
  'app_nahoWikiPlugin_ns_separator' => ':',
  'app_nahoWikiPlugin_max_breadcrumbs' => 5,
  'app_nahoWikiPlugin_breadcrumbs_separator' => ' » ',
  'app_nahoWikiPlugin_include_breadcrumbs' => false,
  'app_nahoWikiPlugin_include_actions' => true,
  'app_nahoWikiPlugin_include_pagename' => false,
  'app_nahoWikiPlugin_include_toc' => true,
  'app_nahoWikiPlugin_routes_register' => true,
  'app_nahoWikiPlugin_wrap_class' => 'nahoWiki',
  'app_nahoWikiPlugin_compress_old_revisions' => true,
  'app_nahoWikiPlugin_internal_links' => array (
  0 => '[[%name% %title%]]',
  1 => '[[%name%]]',
),
  'app_nahoWikiPlugin_internal_link_model' => '[%title%](%link%)',
  'app_nahoWikiPlugin_internal_link_broken_model' => '[%title%(?)](%link%)',
  'app_nahoWikiPlugin_interwiki_links' => array (
  0 => '[[%key%>%name% %title%]]',
  1 => '[[%key%>%name%]]',
),
  'app_nahoWikiPlugin_interwiki_link_model' => '[![%alttext%](%image%) %title%](%link%)',
  'app_nahoWikiPlugin_replace_before' => array (
),
  'app_nahoWikiPlugin_replace_after' => array (
),
  'app_nahoWikiPlugin_strip_tags' => array (
  0 => 'script',
  1 => 'embed',
  2 => 'object',
),
  'app_nahoWikiPlugin_credentials_edit' => array (
),
  'app_nahoWikiPlugin_allow_anonymous_edit' => false,
  'app_nahoWikiPlugin_namespaces' => NULL,
  'app_nahoWikiPlugin_edit_form_name' => 'wiki_edit',
  'app_nahoWikiPlugin_diff_form_name' => 'wiki_diff',
));
