<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/04/09 11:48:25

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=dns',
  'username' => 'root',
  'password' => '',
  'attributes' => 
  array (
    'use_dql_callbacks' => true,
  ),
  'name' => 'doctrine',
)),);
