<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/04/09 13:39:53
sfConfig::add(array(
  'mod_showcase_enabled' => true,
  'mod_showcase_view_class' => 'sfPHP',
  'mod_showcase_is_internal' => false,
));
