<?php
// auto-generated by sfCacheConfigHandler
// date: 2010/02/27 13:08:41
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

