<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/03/21 15:08:05
sfConfig::add(array(
  'mod_user_enabled' => true,
  'mod_user_view_class' => 'sfPHP',
  'mod_user_is_internal' => false,
));
