<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/04/09 13:39:49
sfConfig::add(array(
  'mod_user_enabled' => true,
  'mod_user_view_class' => 'sfPHP',
  'mod_user_is_internal' => false,
));
