<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/03/01 19:07:17
sfConfig::add(array(
  'mod_error_enabled' => true,
  'mod_error_view_class' => 'sfPHP',
  'mod_error_is_internal' => false,
));
