<?php
// auto-generated by sfCacheConfigHandler
// date: 2010/03/21 15:08:06
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

