<?php
// auto-generated by sfCacheConfigHandler
// date: 2010/04/09 13:39:53
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

