<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class expert extends Baseexpert
{
	function getProfessionSlug(){
		return DNS::slugify($this->getProfession());
	}
	function getNameSlug(){
		return DNS::slugify($this->getName());
	}
	function getZoektermen(){
		return implode($this->getTags(), ', ');
	}
	function setZoektermen($data){
		$this->setTags(explode(', ',$data));
	}
}