<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class helpArticle extends BasehelpArticle
{
	function getContent(){
		return sfMarkdown::doConvert($this->getBody());
	}
	
	function getRawContent(){
		return $this->getBody();
	}
}