<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class leerlijnDomein extends BaseleerlijnDomein
{
	function getNameSlug(){
		return DNS::slugify($this->getName());
	}
}