<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserProfile extends BasesfGuardUserProfile
{
	public function getFullName(){
		if($this->getFirstName() AND $this->getLastName()){
			if($this->getPrePosition()){
				return $this->getFirstName().' '.$this->getPrePosition().' '.$this->getLastName();
			}else{
				return $this->getFirstName().' '.$this->getLastName();
			}
		}else{
			return false;
		}
	}
	public function save(Doctrine_Connection $con = null){		
		if(($fileName = $this->getImage())){			
			DNS::resizeImage(80, 80, $fileName, sfConfig::get('sf_upload_dir').'/avatars/', sfConfig::get('sf_upload_dir').'/avatars/');
		}
		
		parent::save($con);
	}
}