<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserProfile extends BasesfGuardUserProfile
{
	public function getFullName(){
		if($this->getFirstName() AND $this->getLastName()){
			if($this->getPrePosition()){
				return $this->getFirstName().' '.$this->getPrePosition().' '.$this->getLastName();
			}else{
				return $this->getFirstName().' '.$this->getLastName();
			}
		}else{
			return false;
		}
	}
}