<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class showcase extends Baseshowcase
{
	function getTitleSlug(){
		return DNS::slugify($this->getTitle());
	}
	public function save(Doctrine_Connection $con = null){		
		if(($fileName = $this->getImage())){			
			DNS::resizeImage(125, 125, $fileName, sfConfig::get('sf_upload_dir').'/showcase/', sfConfig::get('sf_upload_dir').'/showcase/125x125/');
			DNS::resizeImage(120, 120, $fileName, sfConfig::get('sf_upload_dir').'/showcase/', sfConfig::get('sf_upload_dir').'/showcase/120x120/');
		}
		
		parent::save($con);
	}
	
	public function removeImages($filename){
		if(is_file(sfConfig::get('sf_upload_dir').'/showcase/'.$filename)){
			unlink(sfConfig::get('sf_upload_dir').'/showcase/'.$filename);
			unlink(sfConfig::get('sf_upload_dir').'/showcase/125x125/'.$filename);
			unlink(sfConfig::get('sf_upload_dir').'/showcase/120x120/'.$filename);
		}
	}
	public function delete(Doctrine_Connection $con = null){
		if($this->getImage()){
			$this->removeImages($this->getImage());
		}
		parent::delete($con);
	}
	public function set($field, $data, $load=null){
		if(strtolower($field)=='image'){
			if($data != $this->getImage()){
				$this->removeImages($this->getImage());
			}
		}
		parent::set($field, $data, $load);
	}
	
	public function getContent(){
		return sfMarkdown::doConvert($this->getDescription());
	}
}