<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginsfDoctrineSimpleForumForum extends BasesfDoctrineSimpleForumForum
{
	public function getTopicCount()
	{
		// create query
		$topics = Doctrine_Query::create()->from("sfDoctrineSimpleForumTopic")
										  ->where("forum_id=?", $this->id)
										  ->count();
		return $topics;
		
	}
	
	public function getPostCount()
	{
		// create query
		$posts = Doctrine_Query::create()->from("sfDoctrineSimpleForumPost")
										  ->where("forum_id=?", $this->id)
										  ->count();
		return $posts;	
	}
	
	public function getLastPost()
	{
		// create query
		$posts = Doctrine_Query::create()->from("sfDoctrineSimpleForumPost")
										  ->where("forum_id=?", $this->id)
										  ->orderBy("created_at DESC")
										  ->limit(1)
										  ->fetchOne();
		return $posts;			
	}
}