<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginsfDoctrineSimpleForumPost extends BasesfDoctrineSimpleForumPost
{
	public function getCountUserPosts()
	{
		// create query
		$posts = Doctrine_Query::create()->from("sfDoctrineSimpleForumPost")
										  ->where("user_id=?", $this->user_id)
										  ->count();
		return $posts;
	}
	
	public function getReplies()
	{
		$posts = Doctrine_Query::create()->from("sfDoctrineSimpleForumPost")
										  ->orderBy("created_at DESC")
										  ->addWhere("reply_id =?", $this->id)
										  ->execute();

		return (count($posts)>0) ? $posts : array();
	}
}