rendering: ~
security:
  class: sfGuardBasicSecurityFilter

invite:
  class: inviteFilter
returnToSite:                 
  class: returnToSiteFilter
  
# insert your own filters here
sf_google_analytics_plugin:
  class: sfGoogleAnalyticsFilter

cache:     ~
common: {class: sfCombineFilter}
execution: ~