<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUser extends PluginsfGuardUser
{
	public function getFullname(){
		return $this->getProfile()->getFullname();
	}
	public function getFirstName(){
		return $this->getProfile()->getFirstName();
	}
	public function getLastName(){
		return $this->getProfile()->getLastName();
	}
	public function getPreposition(){
		return $this->getProfile()->getPreposition();
	}
	public function getEmail(){
		return $this->getProfile()->getEmail();
	}
	public function getDisplayName(){
		return sprintf('%s (%s)', $this->getFullname(), $this->getUsername());
	}
	public function getInformation($classes=''){
		ob_start();
		?>
		
		<p class="user_information<?php echo is_array($classes) ? ' '.implode($classes, ' ') : $classes; ?>">
		<span><?php echo $this->getFullname();?></span> is al sinds 
		<span><?php echo strftime('%A %e %B %Y', strtotime($this->getCreatedAt())); ?></span> actief op deze site 
		onder de gebruikers naam <span><?php echo $this->getUsername(); ?></span>.
        <span><?php echo $this->getFirstName();?></span> zit in de 
        <?php 
        echo $this->getGroups()->count() == 1?'groep ':'groepen ';
        foreach($this->getGroups() as $i=>$group):
        	?><span><?php echo $group->getName(); ?></span><?php 
        	if($i < $this->getGroups()->count()-2){ 
        		echo ', '; 
        	}else if($i == $this->getGroups()->count()-2){ 
        		echo ' en '; 
        	}else{
        		echo '.'; 
        	}
        endforeach;
        ?>
        </p>
		
		<?php 
		return ob_get_clean();
	}
}