<?php

/**
 * BasesfCombine
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $assets_key
 * @property clob $files
 * 
 * @method string    getAssetsKey()  Returns the current record's "assets_key" value
 * @method clob      getFiles()      Returns the current record's "files" value
 * @method sfCombine setAssetsKey()  Sets the current record's "assets_key" value
 * @method sfCombine setFiles()      Sets the current record's "files" value
 * 
 * @package    leerling
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasesfCombine extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_combine');
        $this->hasColumn('assets_key', 'string', 32, array(
             'type' => 'string',
             'primary' => true,
             'length' => '32',
             ));
        $this->hasColumn('files', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}