generator:
  class: sfDoctrineGenerator
  param:
    model_class:           leerlijnVak
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          leerlijn_vak_vak
    with_doctrine_route:     1

    config:
      actions: ~
      fields:
        name: {label: Naam}
        summary: {label: Samenvating}
        leergebied_id: {label: Leergebied}'
        kern_id: {label: Kern}
      list:
        title: Vak beheer
        display: [=name, summary, leergebied]
      filter: ~
      form:
        display: [name, summary, image, leergebied_id]
      edit:
        title: Aanpassen van %%name%%
      new:
        title: Nieuw Vak