generator:
  class: sfDoctrineGenerator
  param:
    model_class:           leerlijnLeergebied
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          leerlijn_leergebied_leergebied
    with_doctrine_route:     1

    config:
      actions:
        _delete:
          label: Verwijder
        _new:
          label: Nieuw
        _edit:
          label: Wijzig
        _save:
          label: Opslaan
        _save_and_add:
          label: Voeg toe en maak nog een
        _list:
          label: Annuleren
      fields:
        name:
          label: 		Naam
        description:
          label: 		Omschrijving
        image:
          label:		Afbeelding
      list:
        display: [=name, description]
      filter:
        display: [name, description]
      form:    ~
      edit:
        display: [name, description, image]
      new: ~
        #display: [name, description, image]
