<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/02/27 13:07:45

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=dns',
  'username' => 'root',
  'password' => '',
  'name' => 'doctrine',
)),);
