<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/03/01 18:17:07

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=dns',
  'username' => 'root',
  'password' => '',
  'name' => 'doctrine',
)),);
