<?php
// auto-generated by sfRoutingConfigHandler
// date: 2010/02/27 13:07:45
return array(
'sf_doctrine_simple_forum_view_board' => new sfRoute('/forum/board/view/:id/:slug', array (
  'module' => 'sfDoctrineSimpleForum',
  'action' => 'viewBoard',
), array (
), array (
)),
'sf_doctrine_simple_forum_index' => new sfRoute('/forum', array (
  'module' => 'sfDoctrineSimpleForum',
  'action' => 'index',
), array (
), array (
)),
'sf_doctrine_simple_forum_view_topic' => new sfRoute('/forum/topic/view/:id/:slug', array (
  'module' => 'sfDoctrineSimpleForum',
  'action' => 'viewTopic',
), array (
), array (
)),
'sf_doctrine_simple_forum_create_topic' => new sfRoute('/forum/topic/:id/create', array (
  'module' => 'sfDoctrineSimpleForum',
  'action' => 'createTopic',
), array (
), array (
)),
'sf_doctrine_simple_forum_view_latest_feed' => new sfRoute('/forum/latest/feed', array (
  'module' => 'sfDoctrineSimpleForum',
  'action' => 'viewLatestFeed',
  'sf_format' => 'xml',
), array (
), array (
)),
'homepage' => new sfRoute('/', array (
  'action' => 'overview',
  'module' => 'leerlijn',
), array (
), array (
)),
'nieuws' => new sfRoute('/nieuws', array (
  'action' => 'page',
  'module' => 'nieuws',
  'page' => 1,
), array (
), array (
)),
'nieuws_page' => new sfRoute('/nieuws/:page', array (
  'action' => 'page',
  'module' => 'nieuws',
), array (
), array (
)),
'nieuws_item' => new sfRoute('/nieuws/:id/:slug', array (
  'action' => 'show',
  'module' => 'nieuws',
), array (
), array (
)),
'in_the_news' => new sfRoute('/in-het-nieuws', array (
  'action' => 'inTheNews',
  'module' => 'nieuws',
), array (
), array (
)),
'leerlijn_api' => new sfRoute('/api/:sf_format/leerlijn', array (
  'action' => 'overview',
  'module' => 'leerlijn_api',
), array (
  'sf_format' => '(xml)',
), array (
)),
'leerlijn_leergebied_api' => new sfRoute('/api/:sf_format/leerlijn/leergebied/:id/:slug', array (
  'action' => 'leergebiedOverview',
  'module' => 'leerlijn_api',
), array (
  'sf_format' => '(xml)',
), array (
)),
'leerlijn_leerjaar_api' => new sfRoute('/api/:sf_format/leerlijn/leerjaar/:id/:slug', array (
  'action' => 'leerjaarOverview',
  'module' => 'leerlijn_api',
), array (
  'sf_format' => '(xml)',
), array (
)),
'leerlijn_kern_api' => new sfRoute('/api/:sf_format/leerlijn/kern/:id/:slug', array (
  'action' => 'kern',
  'module' => 'leerlijn_api',
), array (
  'sf_format' => '(xml)',
), array (
)),
'leerlijn_vak_api' => new sfRoute('/api/:sf_format/leerlijn/vak/:id/:slug', array (
  'action' => 'vak',
  'module' => 'leerlijn_api',
), array (
  'sf_format' => '(xml)',
), array (
)),
'leerlijn_kernbegrip_api' => new sfRoute('/api/:sf_format/leerlijn/kernbegrip/:id/:slug', array (
  'action' => 'kernbegrip',
  'module' => 'leerlijn_api',
), array (
  'sf_format' => '(xml)',
), array (
)),
'leerlijn_sleutelinzicht_api' => new sfRoute('/api/:sf_format/leerlijn/sleutelinzicht/:id/:slug', array (
  'action' => 'sleutelinzicht',
  'module' => 'leerlijn_api',
), array (
  'sf_format' => '(xml)',
), array (
)),
'leerlijn' => new sfRoute('/leerlijn', array (
  'action' => 'overview',
  'module' => 'leerlijn',
), array (
), array (
)),
'leerlijn_leergebied' => new sfRoute('/leerlijn/leergebied/:id/:slug', array (
  'action' => 'leergebiedOverview',
  'module' => 'leerlijn',
), array (
), array (
)),
'leerlijn_kern' => new sfRoute('/leerlijn/kern/:id/:slug', array (
  'action' => 'kern',
  'module' => 'leerlijn',
), array (
), array (
)),
'leerlijn_vak' => new sfRoute('/leerlijn/vak/:id/:slug', array (
  'action' => 'vak',
  'module' => 'leerlijn',
), array (
), array (
)),
'leerlijn_eindterm' => new sfRoute('/leerkaar/eindterm/:id/:slug', array (
  'action' => 'eindterm',
  'module' => 'leerlijn',
), array (
), array (
)),
'leerlijn_kernbegrip' => new sfRoute('/leerlijn/kernbegrip/:id/:slug', array (
  'action' => 'kernbegrip',
  'module' => 'leerlijn',
), array (
), array (
)),
'leerlijn_sleutelinzicht' => new sfRoute('/leerlijn/sleutelinzicht/:id/:slug', array (
  'action' => 'sleutelinzicht',
  'module' => 'leerlijn',
), array (
), array (
)),
'leerlijn_leerjaar' => new sfRoute('/leerlijn/leerjaar/:id/:slug', array (
  'action' => 'leerjaar',
  'module' => 'leerlijn',
), array (
), array (
)),
'leerlijn_thema' => new sfRoute('/leerlijn/thema/:id/:slug', array (
  'action' => 'thema',
  'module' => 'leerlijn',
), array (
), array (
)),
'sf_guard_signin' => new sfRoute('/login', array (
  'module' => 'user',
  'action' => 'signin',
), array (
), array (
)),
'sf_guard_signout' => new sfRoute('/logout', array (
  'module' => 'sfGuardAuth',
  'action' => 'signout',
), array (
), array (
)),
'sf_guard_password' => new sfRoute('/wachtwoord-vergeten', array (
  'module' => 'user',
  'action' => 'password',
), array (
), array (
)),
'sf_guard_change_password' => new sfRoute('/wachtwoord-veranderen/:auth', array (
  'module' => 'user',
  'action' => 'changepassword',
), array (
), array (
)),
'profile' => new sfRoute('/profiel', array (
  'module' => 'user',
  'action' => 'my',
), array (
), array (
)),
'viewProfile' => new sfRoute('/profiel/:username', array (
  'module' => 'user',
  'action' => 'view',
), array (
), array (
)),
'feedback' => new sfRoute('/feedback', array (
  'module' => 'user',
  'action' => 'feedback',
), array (
), array (
)),
'invite' => new sfRoute('/uitnodigen', array (
  'module' => 'user',
  'action' => 'invite',
), array (
), array (
)),
'invite_accept' => new sfRoute('/uitnodiging/:username', array (
  'module' => 'user',
  'action' => 'inviteAccept',
), array (
), array (
)),
'showcase' => new sfRoute('/wall-of-fame', array (
  'module' => 'showcase',
  'action' => 'wall',
), array (
), array (
)),
'showcase_item' => new sfRoute('/wall-of-fame/:id/:slug', array (
  'module' => 'showcase',
  'action' => 'item',
), array (
), array (
)),
'mailbox' => new sfRoute('/profiel/mailbox', array (
  'module' => 'user',
  'action' => 'mailbox',
), array (
), array (
)),
'api_nieuws_list' => new sfRoute('/api/nieuws/list.:sf_format/:amount', array (
  'module' => 'nieuws',
  'action' => 'apiList',
  'type' => 'xml',
), array (
  'amount' => '\\d+',
), array (
)),
'deadpixel' => new sfRoute('/easteregg/deadpixel', array (
  'module' => 'easteregg',
  'action' => 'deadpixel',
), array (
), array (
)),
'links' => new sfRoute('/links', array (
  'module' => 'links',
  'action' => 'index',
), array (
), array (
)),
'expertbank' => new sfRoute('/expertbank', array (
  'module' => 'expertbank',
  'action' => 'index',
), array (
), array (
)),
'expertbank_show' => new sfRoute('/expertbank/expert/:id/:name_slug/:profession_slug', array (
  'module' => 'expertbank',
  'action' => 'contact',
), array (
), array (
)),
'expertbank_send' => new sfRoute('/expertbank/verstuur/:id/', array (
  'module' => 'expertbank',
  'action' => 'send',
), array (
), array (
)),
'help' => new sfRoute('/help', array (
  'module' => 'help',
  'action' => 'index',
  'id' => 1,
), array (
), array (
)),
'help_page' => new sfRoute('/help/:id/:slug', array (
  'module' => 'help',
  'action' => 'page',
), array (
), array (
)),
'ideabox' => new sfRoute('/ideeenbox', array (
  'module' => 'ideabox',
  'action' => 'index',
), array (
), array (
)),
'sf_doctrine_simple_forum_view_board_noslug' => new sfRoute('/forum/board/view/:id/', array (
  'module' => 'sfDoctrineSimpleForum',
  'action' => 'viewBoard',
), array (
), array (
)),
'default' => new sfRoute('/:module/:action/*', array (
), array (
), array (
)),
);
