<?php
// auto-generated by sfSecurityConfigHandler
// date: 2010/02/27 13:07:46
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'leerlijn_use',
        1 => 'leerlijn_beta',
      ),
    ),
  ),
);
