<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/03/01 18:59:06
sfConfig::add(array(
  'mod_leerlijn_enabled' => true,
  'mod_leerlijn_view_class' => 'sfPHP',
  'mod_leerlijn_is_internal' => false,
));
